"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const products_controller_1 = require("../controllers/products-controller");
const router = (0, express_1.Router)();
router.post("/products-cache", products_controller_1.show);
router.get("/products-cache/sku/:sku", products_controller_1.showBySku);
router.get("/products-cache/partNumber/:partnumber", products_controller_1.showByPartnumber);
router.post("/products-cache/partNumber/:partnumber", products_controller_1.showByPartNumberAndProvider);
router.post("/products-cache/category", products_controller_1.showByCategory);
exports.default = router;
